import jsPDF from "jspdf";

export function exportChatToPDF(
  messages: { role: "user" | "assistant"; content: string }[]
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = 30;
  let questionNumber = 0;

  // Cover Page
  doc.setFillColor(15, 17, 21);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(231, 233, 234);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("Pungde", pageWidth / 2, 100, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("AI Farming Assistant", pageWidth / 2, 115, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Consultation Report", pageWidth / 2, 130, { align: "center" });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, 140, {
    align: "center",
  });

  // Content Page
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Farming Consultation Report", margin, yPosition);
  yPosition += 15;

  // Messages as Q&A
  messages.forEach((msg) => {
    if (msg.role === "assistant" && msg.content.includes("Namaste")) {
      return; // Skip greeting
    }

    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }

    if (msg.role === "user") {
      questionNumber++;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(45, 49, 56);
      doc.text(`Q${questionNumber}:`, margin, yPosition);
      yPosition += 7;
    } else {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(10, 100, 10);
      doc.text("Answer:", margin, yPosition);
      yPosition += 7;
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);

    // Clean markdown but keep text readable
    const cleanText = msg.content
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/\*(.*?)\*/g, "$1")
      .replace(/#{1,6}\s/g, "")
      .replace(/`{1,3}(.*?)`{1,3}/g, "$1");

    const lines = doc.splitTextToSize(cleanText, maxWidth);
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });

    yPosition += 10;
  });

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by Pungde AI Farming Assistant",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  doc.save(`Pungde-${new Date().toISOString().split("T")[0]}.pdf`);
}
